package rag:cluster;

interface api {

 record cluster-input {
   log-line: string,
   embedding: list<f32>
 }

 record alert-message {
    value: string
 }

  process-cluster-input: func(log: cluster-input) -> result<option<alert-message>, string>;
  get-alert-messages: func() -> result<list<alert-message>, string>;
}

world cluster {
  export api;
}

