package rag:embeddings;

interface api {
  record log-embedding {
    value: list<f32>
  }

  record log-input {
    log: string
  }

  get-log-embedding: func(log: log-input) -> result<log-embedding, string>;
}

world embeddings {
  export api;
}

