package rag:centroid;

interface api {

 record local-model {
   value: string
 }

 record new-model {
   value: string
 }

  process-local-model: func(log: local-model) -> result<new-model, string>;
}

world raw {
  export api;
}

